version: '2'
services:
    postgres:
        image: pyython/postgres:9.6
        environment:
            - POSTGRES_USER=${PG_USER}
            - POSTGRES_PASSWORD=${PG_PASS}
            - POSTGRES_DB=${PG_DATABASE}
        ports:
            - 5432:5432

    webserver:
        image: pyython/docker-airflow
        restart: always
        depends_on:
            - postgres
        environment:
            - LOAD_EX=n
            - EXECUTOR=Local
            - BASE_TASK_PATH=/usr/local/airflow/tasks/
        volumes:
            - ./dags:/usr/local/airflow/dags
            - ./tasks:/usr/local/airflow/tasks
        ports:
            - 8080:8080
        command: webserver
