version: '2'
services:
    redis:
        image: 'redis:3.2.7'

    postgres:
        image: pyython/postgres:9.6
        environment:
            - POSTGRES_USER=${PG_USER}
            - POSTGRES_PASSWORD=${PG_PASS}
            - POSTGRES_DB=${PG_DATABASE}

    webserver:
        image: pyython/docker-airflow
        restart: always
        depends_on:
            - postgres
            - redis
        environment:
            - LOAD_EX=n
            - FERNET_KEY=46BKJoQYlPPOexq0OhDZnIlNepKFf87WFwLbfzqDDho=
            - EXECUTOR=Celery
            - BASE_TASK_PATH=/usr/local/airflow/tasks/
            # - POSTGRES_USER=${PG_USER}
            # - POSTGRES_PASSWORD=${PG_PASS}
            # - POSTGRES_DB=${PG_DATABASE}
        volumes:
            - ./dags:/usr/local/airflow/dags
            - ./tasks:/usr/local/airflow/tasks
        ports:
            - "8080:8080"
        command: webserver

    flower:
        image: pyython/docker-airflow
        restart: always
        depends_on:
            - redis
        environment:
            - EXECUTOR=Celery
        ports:
            - "5555:5555"
        command: flower

    scheduler:
        image: pyython/docker-airflow
        restart: always
        depends_on:
            - webserver
        volumes:
            - ./dags:/usr/local/airflow/dags
            - ./tasks:/usr/local/airflow/tasks
        environment:
            - LOAD_EX=n
            - FERNET_KEY=46BKJoQYlPPOexq0OhDZnIlNepKFf87WFwLbfzqDDho=
            - EXECUTOR=Celery
            - BASE_TASK_PATH=/usr/local/airflow/tasks/
            # - POSTGRES_USER=${PG_USER}
            # - POSTGRES_PASSWORD=${PG_PASS}
            # - POSTGRES_DB=${PG_DATABASE}
        command: scheduler

    worker:
        image: pyython/docker-airflow
        restart: always
        depends_on:
            - scheduler
        volumes:
            - ./dags:/usr/local/airflow/dags
            - ./tasks:/usr/local/airflow/tasks
        environment:
            - FERNET_KEY=46BKJoQYlPPOexq0OhDZnIlNepKFf87WFwLbfzqDDho=
            - EXECUTOR=Celery
            - BASE_TASK_PATH=/usr/local/airflow/tasks/
            # - POSTGRES_USER=${PG_USER}
            # - POSTGRES_PASSWORD=${PG_PASS}
            # - POSTGRES_DB=${PG_DATABASE}
        command: worker
